// Servicio de negocio para template macro catalog.
export type TemplateMacroGroup = {
  key: "CONFIRMACION_RESERVA" | "CONTRATO" | "FACTURA";
  title: string;
  macros: Array<{ macro: string; description: string }>;
};

export const TEMPLATE_MACRO_GROUPS: TemplateMacroGroup[] = [
  {
    key: "CONFIRMACION_RESERVA",
    title: "Confirmación de reserva",
    macros: [
      { macro: "{resNum}", description: "Número de reserva (alternativa: {reservation_number}, {docNum})." },
      { macro: "{conductorNombre}", description: "Nombre cliente/conductor (alternativa: {customer_name}, {driver})." },
      { macro: "{eFechaHora}", description: "Fecha y hora entrega (alternativa: {delivery_at})." },
      { macro: "{eFecha}", description: "Fecha entrega (alternativa: {delivery_date})." },
      { macro: "{eHora}", description: "Hora entrega (alternativa: {delivery_time})." },
      { macro: "{eLugar}", description: "Lugar entrega (alternativa: {delivery_place})." },
      { macro: "{rFechaHora}", description: "Fecha y hora recogida (alternativa: {pickup_at})." },
      { macro: "{rFecha}", description: "Fecha recogida (alternativa: {pickup_date})." },
      { macro: "{rHora}", description: "Hora recogida (alternativa: {pickup_time})." },
      { macro: "{rLugar}", description: "Lugar recogida (alternativa: {pickup_place})." },
      { macro: "{grupoFac}", description: "Grupo vehículo (alternativa: {grupo}, {billed_car_group})." },
      { macro: "{matricula}", description: "Matrícula asignada (alternativa: {assigned_plate})." },
      { macro: "{dias}", description: "Días facturados (alternativa: {billed_days})." },
      { macro: "{ocupacion}", description: "Importe base (alternativa: {base_amount})." },
      { macro: "{extras}", description: "Importe extras (alternativa: {extras_amount})." },
      { macro: "{combustible}", description: "Importe combustible (alternativa: {fuel_amount})." },
      { macro: "{importe}", description: "Total reserva (alternativa: {total_amount})." },
      { macro: "{franquicia}", description: "Franquicia (alternativa: {deductible})." },
      { macro: "{obs}", description: "Observaciones (alternativa: {conductorObs}, {observations})." },
      { macro: "{vuelo}", description: "Nº vuelo (alternativa: {conductorVuelo}, {delivery_flight_number})." },
      { macro: "{extra#01}", description: "Nombre extra 1 (hasta {extra#06})." },
      { macro: "{extra#01unit}", description: "Unidades extra 1 (hasta {extra#06unit})." },
      { macro: "{extra#01price}", description: "Precio unitario extra 1 (hasta {extra#06price})." },
      { macro: "{extra#01total}", description: "Total extra 1 (hasta {extra#06total})." },
      { macro: "{company_document_name}", description: "Nombre documental empresa (alternativa: {company_name})." },
      { macro: "{company_tax_id}", description: "NIF/CIF empresa." },
      { macro: "{company_fiscal_address}", description: "Dirección fiscal empresa." },
      { macro: "{company_email_from}", description: "Email empresa (alternativa: {correo@dominio.com})." },
      { macro: "{company_phone}", description: "Teléfono empresa." },
      { macro: "{company_website}", description: "Web empresa." },
      { macro: "{company_document_footer}", description: "Pie documental configurado." },
      { macro: "{company_logo_data_url}", description: "Logo (data URL)." },
      { macro: "{company_brand_primary_color}", description: "Color principal marca." },
      { macro: "{company_brand_secondary_color}", description: "Color secundario marca." },
    ],
  },
  {
    key: "CONTRATO",
    title: "Contrato (preimpresión HTML)",
    macros: [
      { macro: "{company_document_name}", description: "Nombre documental empresa (alternativa: {company_name})." },
      { macro: "{company_tax_id}", description: "NIF/CIF empresa." },
      { macro: "{company_fiscal_address}", description: "Dirección fiscal empresa." },
      { macro: "{company_phone}", description: "Teléfono empresa." },
      { macro: "{company_website}", description: "Web empresa." },
    ],
  },
  {
    key: "FACTURA",
    title: "Factura",
    macros: [
      { macro: "{invoice_number}", description: "Número de factura." },
      { macro: "{invoice_name}", description: "Nombre/Concepto de factura." },
      { macro: "{issued_at}", description: "Fecha de emisión." },
      { macro: "{contract_number}", description: "Número de contrato." },
      { macro: "{customer_name}", description: "Cliente facturado." },
      { macro: "{base_amount}", description: "Base imponible." },
      { macro: "{extras_amount}", description: "Extras." },
      { macro: "{insurance_amount}", description: "Seguros." },
      { macro: "{penalties_amount}", description: "Penalizaciones." },
      { macro: "{iva_percent}", description: "Porcentaje IVA." },
      { macro: "{iva_amount}", description: "Importe IVA." },
      { macro: "{total_amount}", description: "Total factura." },
      { macro: "{company_document_name}", description: "Nombre documental empresa (alternativa: {company_name})." },
      { macro: "{company_tax_id}", description: "NIF/CIF empresa." },
      { macro: "{company_fiscal_address}", description: "Dirección fiscal empresa." },
      { macro: "{company_email_from}", description: "Email de empresa." },
      { macro: "{company_phone}", description: "Teléfono empresa." },
      { macro: "{company_website}", description: "Web empresa." },
      { macro: "{company_document_footer}", description: "Pie documental configurado." },
      { macro: "{company_logo_data_url}", description: "Logo (data URL)." },
      { macro: "{company_brand_primary_color}", description: "Color principal marca." },
      { macro: "{company_brand_secondary_color}", description: "Color secundario marca." },
    ],
  },
];
